### ISSUE TITLE
Using blueprint on a wandering trader causes uncaught error

### ISSUE THREAD

**Issue by Reldeam** [Reldeam/CustomVillagerTrades#6]
```
[15:40:25 ERROR]: Could not pass event VillagerAcquireTradeEvent to CustomVillagerTrades v1.6-SNAPSHOT
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_18_R1.entity.CraftWanderingTrader cannot be cast to class org.bukkit.entity.Villager (org.bukkit.craftbukkit.v1_18_R1.entity.CraftWanderingTrader and org.bukkit.entity.Villager are in unnamed module of loader java.net.URLClassLoader @504bae78)
        at online.meinkraft.customvillagertrades.listener.VillagerAcquireTradeListener.onVillagerAcquireTrade(VillagerAcquireTradeListener.java:30) ~[customvillagertrades-1.6-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor5.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-175]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.npc.WanderingTrader.updateTrades(WanderingTrader.java:149) ~[?:?]
        at net.minecraft.world.entity.npc.AbstractVillager.getOffers(AbstractVillager.java:129) ~[?:?]
        at net.minecraft.world.entity.npc.WanderingTrader.mobInteract(WanderingTrader.java:116) ~[?:?]
        at net.minecraft.world.entity.Mob.interact(Mob.java:1254) ~[?:?]
        at net.minecraft.world.entity.player.Player.interactOn(Player.java:1081) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.performInteraction(ServerGamePacketListenerImpl.java:2487) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2506) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2448) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-175]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-175]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-175]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-175]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-175]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-175]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-175]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-175]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Reldeam** [comment]
Using the reroll/reset tool causes the same error.

**Comment by Reldeam** [comment]
Fixed: https://github.com/Reldeam/CustomVillagerTrades/commit/b4707843f9b5513f0ff83c6d4277910ddfcc017d
